services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tourna-master'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5432:5432'

volumes:
  postgres-data: